import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Catalogo Dhermica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<div className="flex items-center justify-center bg-[#484450] p-1">
  <Image 
    src="/logo.png" 
    alt="Logo" 
    width={300} 
    height={300}
    className="w-56 md:w-72 lg:w-80 h-auto"
  />
</div>

        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
